name: Release tagged commits
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        GOOS:
          - linux
          - darwin
          - windows
          - plan9
          - openbsd
          - freebsd
        GOARCH:
          - '386'
          - amd64
          - arm
          - arm64
        exclude:
          - GOOS: darwin
            GOARCH: '386'
          - GOOS: darwin
            GOARCH: arm
          - GOOS: plan9
            GOARCH: arm64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - run: make build GOOS=${{matrix.GOOS}} GOARCH=${{matrix.GOARCH}}
      - uses: actions/upload-artifact@v3
        with:
          name: tg2fedi.${{matrix.GOOS}}.${{matrix.GOARCH}}
          path: bin/tg2fedi.${{matrix.GOOS}}.${{matrix.GOARCH}}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**

